baseurl = "http://salmonet.org/"
languageCode = "en-us"
title = "SalmoNet2"
theme = "SalmoNet"
Paginate = 10

[params]
  description = "Demo site for a hugo theme"
  google_analytics = "UA-73347324-4"
